### ISSUE TITLE
You can make reservations only during opening hours (Monday-Friday from 10am to 10pm, Saturday-Sunday from 12pm to midnight)

### ISSUE THREAD

**Issue by SzczypekJ** [AGH-Evil-Inc/TableReservation#55]

**Comment by Kri5t0fK** [comment]
done in: 2428eb48c11dacdb2e1f2176973ef86938f0f152
https://github.com/AGH-Evil-Inc/TableReservation/blob/2428eb48c11dacdb2e1f2176973ef86938f0f152/backend/Marshmallow.py#L60-L70
